language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - cd transport
  - go get -t ./...
script:
  - cd transport
  - $HOME/gopath/bin/goveralls -service=travis-ci